name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r aegis2.0_patched/aegis2.0/requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 sentinal/ --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run tests
        run: |
          python -m unittest discover sentinal/tests
